### ISSUE TITLE
allennlp-guide/quick_start/predict.py need to update

### ISSUE THREAD

**Issue by JackKuo666** [allenai/allennlp-guide#186]
problem: 
    when i run `python predict.py`, The following error occurs:
```py
Traceback (most recent call last):
  File "F:/code/learn_allennlp/1.classification/predict.py", line 181, in <module>
    output = predictor.predict("A good movie!")
  File "F:/code/learn_allennlp/1.classification/predict.py", line 167, in predict
    return self.predict_json({"sentence": sentence})
  File "D:\ProgramData\Miniconda3\envs\allennlp\lib\site-packages\allennlp\predictors\predictor.py", line 54, in predict_json
    instance = self._json_to_instance(inputs)
  File "F:/code/learn_allennlp/1.classification/predict.py", line 171, in _json_to_instance
    return self._dataset_reader.text_to_instance(sentence)
  File "D:\ProgramData\Miniconda3\envs\allennlp\lib\site-packages\allennlp\data\dataset_readers\dataset_reader.py", line 230, in text_to_instance
    raise NotImplementedError
NotImplementedError

Process finished with exit code 1
```
i find the `class ClassificationTsvReader(DatasetReader):` need add a `def text_to_instance(self, text: str, label: str = None) -> Instance:` To accommodate predictive inputs:
```py
    def text_to_instance(self, text: str, label: str = None) -> Instance:
        tokens = self.tokenizer.tokenize(text)
        if self.max_tokens:
            tokens = tokens[: self.max_tokens]
        text_field = TextField(tokens, self.token_indexers)
        fields = {'text': text_field}
        if label:
            fields['label'] = LabelField(label)
        return Instance(fields)

    def _read(self, file_path: str) -> Iterable[Instance]:
        with open(file_path, 'r') as lines:
            for line in lines:
                text, sentiment = line.strip().split('\t')
                yield self.text_to_instance(text, sentiment)
```
i find the `class SimpleClassifier(Model):` need update `def forward(self, text: TextFieldTensors, label: torch.Tensor = None) -> Dict[str, torch.Tensor]:` To accommodate predictive inputs:
```py
    def forward(
        self, text: TextFieldTensors, label: torch.Tensor = None
    ) -> Dict[str, torch.Tensor]:
        # Shape: (batch_size, num_tokens, embedding_dim)
        embedded_text = self.embedder(text)
        # Shape: (batch_size, num_tokens)
        mask = util.get_text_field_mask(text)
        # Shape: (batch_size, encoding_dim)
        encoded_text = self.encoder(embedded_text, mask)
        # Shape: (batch_size, num_labels)
        logits = self.classifier(encoded_text)
        # Shape: (batch_size, num_labels)
        probs = torch.nn.functional.softmax(logits)
        output = {'probs': probs}
        if label is not None:
            self.accuracy(logits, label)
            # Shape: (1,)
            output['loss'] = torch.nn.functional.cross_entropy(logits, label)
        return output
```

**Comment by JackKuo666** [comment]
so i write a pr to solve : [Update quick start predict py #187](https://github.com/allenai/allennlp-guide/pull/187)
